# .erb-lint_rubocop.yml
Lint/UselessAssignment:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/EndOfLine:
  Enabled: false
