inherit_from:
  - .rubocop/layout.yml
  - .rubocop/metrics.yml
  - .rubocop/naming.yml
  - .rubocop/rails.yml
  - .rubocop/rspec_rails.yml
  - .rubocop/rspec.yml
  - .rubocop/style.yml
  - .rubocop/custom.yml
  - .rubocop/strict.yml
  - .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml

AllCops:
  NewCops: disable
  Exclude:
    - node_modules/**/*
    - public/**/*
    - vendor/**/*
    # - 'db/**/*'
    # - 'node_modules/**/*'
    # - 'vendor/bundle/**/*'
  DisplayStyleGuide: true
  ExtraDetails: true
  SuggestExtensions: false
  TargetRubyVersion: 3.3.0

Rails:
  Enabled: true # enable rubocop-rails cops
RSpec:
  Enabled: true # enable rubocop-rspec cops
RSpec/DescribeClass:
  Enabled: false # ignore missing comments on classes
Bundler/DuplicatedGem:
  Enabled: false # ignore duplicated gem errors because we will have duplicated gems when dual booting
