ruby_version:
fix: false # default: false
parallel: true # default: false
format: progress # default: Standard::Formatter
default_ignores: false # default: true

ignore: # default: []
  - "lib/**/*":
      - Style/IdenticalConditionalBranches # these are just easier to read sometimes
      - Style/IfInsideElse # these are just easier to read sometimes
      - Standard/SemanticBlocks # not valid in older Ruby
      - Style/Alias # This isn't always right and alias and alias_method can have different usage
      - Style/RedundantRegexpEscape # fix later, enforcement changed
      - Layout/ArrayAlignment # WTF all of master broken from a few changes in rubo
      - Performance/RegexpMatch # Rubocop / standardrb have this WRONG for Ruby 2.3/2.4 not compatiable
      - Style/GlobalStdStream # Rubocop / standardrb have this WRONG for Ruby 2.3/2.4 not compatiable
  - "vendor/**/*"
  - "pkg/**/*"
  - "test/**/*":
      - Layout/AlignHash
      - Style/GlobalVars
      - Lint/InterpolationCheck # a test is verifying comments
      - Standard/SemanticBlocks # not valid in older Ruby
      - Layout/ArrayAlignment # ruby 2.3 / modern seem to dissagree on rubocop/standardrb
  - "test/benchmarks/benchmark.rake":
      - Lint/UselessAssignment # oddity of memory benchmarking

plugins:
  - standard-rails
extend_config:
  - .rubocop/rspec.yml
  - .rubocop/custom.yml
